Ex15 js oop
DarkProDen/external-courses pull request #13
Opened 2018-12-03 22:29 UTC by DarkProDen

2018-12-04 19:10 UTC, eugrdn requested changes

2018-12-04 19:10 UTC, eugrdn commented on src/ex15_js-oop/Classwork.js
> +Square.prototype.getPerimeter = function () {
не сохранил конструктор, и ниже тоже

2018-12-04 19:10 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +    this.name = name;
```
this.name = ...
this.type = ...
this.power = ...
this.enabled = ...
```
повторяется во всех конструкторах: переиспользуй родительский

2018-12-04 19:10 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +Chandelier.prototype = new Device();
так лучше не делать, прочитай https://learn.javascript.ru/class-inheritance#polnyy-kod-nasledovaniya про неправильный вариант

2018-12-04 19:10 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +    for (let i = 0; i < Object(this.lamps).length; i++) {
зачем обертка `Object(...)`? и ниже

2018-12-04 19:10 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +    devices.forEach(device => {
коммент?

2018-12-04 19:10 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +room.devices.forEach(device => {
2 аргумент колбека -- index, не нужно создать глобальную переменную

2018-12-05 16:18 UTC, DarkProDen commented on src/ex15_js-oop/Task15.js
> +    for (let i = 0; i < Object(this.lamps).length; i++) {
я пытался сначала this.lamps.length . выдает ошибку.

2018-12-05 16:39 UTC, DarkProDen commented on src/ex15_js-oop/Classwork.js
> +Square.prototype.getPerimeter = function () {
Исправил (вроди)

2018-12-05 18:00 UTC, DarkProDen commented
Исправил все

2018-12-05 18:43 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +    for (let i = 0; i < this.lamps.length; i++) {
используй forEach

2018-12-05 18:43 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +    this.devices = [];
а почему не просто `this.devices = devices`?

2018-12-05 18:43 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +    for (let i = 0; i < this.devices.length; i++) {
используй reduce

2018-12-05 18:43 UTC, eugrdn commented on src/ex15_js-oop/Task15.js
> +    for (let i = 0; i < this.devices.length; i++) {
используй find

2018-12-06 08:05 UTC, DarkProDen commented on src/ex15_js-oop/Task15.js
> +    for (let i = 0; i < this.devices.length; i++) {
Сделал все

2018-12-06 12:09 UTC, eugrdn approved these changes

2018-12-06 12:09 UTC, merged